In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [4]:
grades =np.array ([[85,70,82],[75,92,85],[66,67,65],[87,90,60]])

In [5]:
grades

array([[85, 70, 82],
       [75, 92, 85],
       [66, 67, 65],
       [87, 90, 60]])

In [6]:
weights = np.array([0.3,0.4,0.3])

In [7]:
np.dot(grades,weights)

array([78.1, 84.8, 66.1, 80.1])

In [8]:
L=np.array([3,5,7,9])

In [9]:
L

array([3, 5, 7, 9])