In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A =np.random.randn(100)

In [3]:
A

array([ 1.31769297, -0.75809793,  0.31937884, -0.26810646,  0.57968438,
       -0.60294098,  2.87013687, -0.215058  , -0.76425353,  1.22218281,
       -1.04693769,  1.28577171, -0.64426352,  0.01460496, -0.49532992,
       -0.06662117,  0.30516975, -3.33253161,  1.69574933, -0.63835158,
       -0.34379867,  0.85259047,  1.91122408,  0.22371285,  0.03654177,
        0.02022975,  0.77373024, -0.01886295, -0.49104227, -0.21978659,
        0.27001056, -0.98140845, -0.81173979, -1.88151234,  1.41321032,
       -2.04470954, -0.82803626,  1.79371592, -0.53375016,  0.2710813 ,
        0.61411319,  0.33026802, -1.01290269, -0.27800098,  0.35583548,
        0.22324814, -1.44969621,  1.63283849,  0.96382513, -0.461973  ,
        2.04545931, -0.50800844, -0.5633781 , -0.81341505, -1.98226073,
        0.14095202,  0.19830273, -3.23772135, -0.28506342, -0.08255218,
        0.54587959, -1.91667682, -0.59902531, -1.68141529,  1.43717675,
       -0.91278906, -2.29187124, -0.14944994,  1.11368156, -0.47

In [4]:
A = 10*A+50

In [5]:
A

array([63.17692968, 42.41902073, 53.19378836, 47.3189354 , 55.79684384,
       43.97059022, 78.70136868, 47.84942001, 42.35746468, 62.22182812,
       39.53062313, 62.85771708, 43.55736478, 50.14604962, 45.04670082,
       49.33378825, 53.05169746, 16.67468395, 66.95749335, 43.61648422,
       46.56201331, 58.52590468, 69.11224075, 52.23712849, 50.36541765,
       50.20229752, 57.73730242, 49.81137049, 45.08957731, 47.80213411,
       52.70010564, 40.1859155 , 41.88260205, 31.18487663, 64.13210322,
       29.55290464, 41.71963739, 67.93715924, 44.66249839, 52.71081298,
       56.14113186, 53.30268017, 39.87097305, 47.2199902 , 53.55835481,
       52.23248144, 35.50303791, 66.32838489, 59.63825134, 45.38027005,
       70.45459308, 44.91991564, 44.366219  , 41.86584954, 30.17739273,
       51.4095202 , 51.9830273 , 17.62278651, 47.14936579, 49.1744782 ,
       55.45879589, 30.8332318 , 44.00974687, 33.18584709, 64.37176746,
       40.87210937, 27.08128763, 48.50550059, 61.13681557, 45.25

In [6]:
A.shape

(100,)

In [10]:
A.shape =(5,20) #20列,5行

In [11]:
A

array([[63.17692968, 42.41902073, 53.19378836, 47.3189354 , 55.79684384,
        43.97059022, 78.70136868, 47.84942001, 42.35746468, 62.22182812,
        39.53062313, 62.85771708, 43.55736478, 50.14604962, 45.04670082,
        49.33378825, 53.05169746, 16.67468395, 66.95749335, 43.61648422],
       [46.56201331, 58.52590468, 69.11224075, 52.23712849, 50.36541765,
        50.20229752, 57.73730242, 49.81137049, 45.08957731, 47.80213411,
        52.70010564, 40.1859155 , 41.88260205, 31.18487663, 64.13210322,
        29.55290464, 41.71963739, 67.93715924, 44.66249839, 52.71081298],
       [56.14113186, 53.30268017, 39.87097305, 47.2199902 , 53.55835481,
        52.23248144, 35.50303791, 66.32838489, 59.63825134, 45.38027005,
        70.45459308, 44.91991564, 44.366219  , 41.86584954, 30.17739273,
        51.4095202 , 51.9830273 , 17.62278651, 47.14936579, 49.1744782 ],
       [55.45879589, 30.8332318 , 44.00974687, 33.18584709, 64.37176746,
        40.87210937, 27.08128763, 48.50550059, 6

In [12]:
A.reshape(100,1) #100列,1行

array([[63.17692968],
       [42.41902073],
       [53.19378836],
       [47.3189354 ],
       [55.79684384],
       [43.97059022],
       [78.70136868],
       [47.84942001],
       [42.35746468],
       [62.22182812],
       [39.53062313],
       [62.85771708],
       [43.55736478],
       [50.14604962],
       [45.04670082],
       [49.33378825],
       [53.05169746],
       [16.67468395],
       [66.95749335],
       [43.61648422],
       [46.56201331],
       [58.52590468],
       [69.11224075],
       [52.23712849],
       [50.36541765],
       [50.20229752],
       [57.73730242],
       [49.81137049],
       [45.08957731],
       [47.80213411],
       [52.70010564],
       [40.1859155 ],
       [41.88260205],
       [31.18487663],
       [64.13210322],
       [29.55290464],
       [41.71963739],
       [67.93715924],
       [44.66249839],
       [52.71081298],
       [56.14113186],
       [53.30268017],
       [39.87097305],
       [47.2199902 ],
       [53.55835481],
       [52